---

stages:
  - build

build:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t yourdocsascode/docsascode:${CI_COMMIT_REF_NAME} .
    - docker push yourdocsascode/docsascode:${CI_COMMIT_REF_NAME}
